jobs:
  
  validate:
    macnhine: true 
    steps:
      - checkout
      
      - run:
          command: |
            docker pull bridgecrew/checkov
            docker run --rm -w /src -v $(pwd):/src bridgecrew/checkov -d aws -o json | tee checkov-output.json
          
      - store_artifacts:
          path: checkov-output.json
          destination: checkov-output
          when: always 


  build:
    machine: true
    steps:
      - checkout
      - run: echo "This is a build step"

  test:
    machine: true
    steps:
      - checkout
      - run: echo "This is a test step"

  integration:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
          when: on_fail

  prod:
    machine: true
    steps:
      - checkout
      - run: echo "This is a deploy step"

workflows:
  version: 2
  terraform:
    jobs:
      - validate
      - build:
          requires:
            - validate
      - test:
          requires:
            - build 
      - integration:
          requires:
            - test
      - prod:
          type: approval
          requires:
            - integration